### ISSUE TITLE
400 Bad Request - invalid_grant authentication failure

### ISSUE THREAD

**Issue by camaech** [omniphx/forrest#274]
```GuzzleHttp\Exception\ClientException · Client error: `POST https://test.salesforce.com/services/oauth2/token` resulted in a `400 Bad Request` response: {"error":"invalid_grant","error_description":"authentication failure"}```

I get this error when trying to batch a lot of upserts into Salesforce. I'm using the UserPassword authentication method. My question is why doesn't it just automatically authenticate?

Or why can't I just wrap it in a try/catch and manually refresh the authentication token?

To me it seems like the try/catch should occur in your getAuthToken method of UserPassword.php.

**Comment by omniphx** [comment]
This library doesn't authenticate automatically because Salesforce has a limited number of API calls per 24 hours and if exceeded the whole org will grind to a halt.  I choose to build it this way so developers could choose how they want to implement authentication. Trust me, it's no fun to shut down your whole company in the middle of the biggest sales day of the year aka Black Friday. Anyway, hope that provides some clarity into the decision. Generally, I think it's a good idea to give control to devs over automagically doing things. Especially if those things come with risk.

For the `invalid_grant` error--is this always happening?  Or does it start appearing after x number of upserts? I would also take a look at the logs in Salesforce login history to see if there are more details there. Sometimes these errors are due to IP restrictions

**Comment by caseydwyer** [comment]
> I would also take a look at the logs in Salesforce login history

That's a very good tip. The `400 Bad Request`s are pretty vague, so the Login History can help give some valuable context around when/why a request failed. For (my own inevitable, future) reference, that can be found in your org's setup:

`https://your-org.lightning.force.com/lightning/setup/OrgLoginHistory/home`

@omniphx - thanks for that, and for your work on maintaining this project! Really appreciate your dedication, here. 👍
