### ISSUE TITLE
Client error: `POST https://login.salesforce.com/services/oauth2/token` resulted in a `400 Bad Request` response: {"error":"invalid_grant","error_description":"user hasn't approved this consumer"}

### ISSUE THREAD

**Issue by CharbelJ** [omniphx/forrest#278]
I have followed all the step-by-step guide to complete JWT authentication flow.
When I hit the endpoint

```
Route::get('/authenticate', function() {
    return Forrest::authenticate();
});
```

I get 
```
Client error: `POST https://login.salesforce.com/services/oauth2/token` resulted in a `400 Bad Request` response: {"error":"invalid_grant","error_description":"user hasn't approved this consumer"}
```

Please advise

**Comment by omniphx** [comment]
The error message saying you haven't pre-approved the user you are trying to login as. Try following these steps: https://github.com/omniphx/forrest#jwt-authentication-flow

**Comment by omniphx** [comment]
Actually looks like it could also be due to the user never having logged in before. Here's some additional steps you could try:
https://salesforce.stackexchange.com/questions/31969/oauth-2-0-jwt-bearer-token-flow-giving-a-user-hasnt-approved-this-consumer-erro
https://salesforce.stackexchange.com/questions/184363/salesforce-jwt-user-hasnt-approved-this-consumer-again

**Comment by CharbelJ** [comment]
Thank you @omniphx I had a quick look and the thing that was initially wrong on my end was that Salesforce Login Url for production should be different than the one for sandbox, this is why I was getting this error.

```
// for sandbox
SF_LOGIN_URL=https://test.salesforce.com
```

```
// for production
SF_LOGIN_URL=https://login.salesforce.com
```
