### ISSUE TITLE
UserPassword Authenticate not making use of token store.

### ISSUE THREAD

**Issue by jreeter** [omniphx/forrest#325]
@omniphx I'm a bit surprised that the authenticate method in UserPassword doesn't make use of the token store. This could be very beneficial for job processing that executes often and could help avoid exceeding the login limit for a set of Salesforce credentials.

Is there a reason for it not using the store and skipping the auth call if there's a token present in the store? If it's expired the refresh code path on requests will take care of grabbing a new token.

**Comment by omniphx** [comment]
Hi @jreeter, it's been a while since I originally implemented the auth methods but I believe a lot of my design decisions were due to the fact that Salesforce limits the number of API calls you can make. I've had bad experiences in the past where my entire org was shut down for ~24 hours due to exceeding the number of API calls allowed. I would feel terrible if this type of thing happened to someone using my library.

If you wanted to reauthenticate in situations where a token was expired in your session or cache, I would recommend catching the exception (`MissingTokenException`) and retrying:

```php
try {
    return Forrest::query('SELECT Id, Name FROM Account');
} catch (Omniphx\Forrest\Exceptions\MissingTokenException $e) {
    Forrest::authenticate();
    return Forrest::query('SELECT Id, Name FROM Account');
} catch (Exception $e) {
    return $e->getMessage();
}
```
