### ISSUE TITLE
Atomic transaction

### ISSUE THREAD

**Issue by Vasiharan** [omniphx/forrest#52]
Hi, 

I am using your forrest package to integrate with salesforce, so far it is has been great. Thanks for the package!

I was wondering if it is possible to do atomic transaction while using the rest api within this package? I am asking because I want to test my salesforce repository but want to roll back after a test runs.

If not, do you know if there is an easy way to clean the db back to a predefined state so that I can easily run my tests against a know valid state?

Thanks,
Vasi

**Comment by omniphx** [comment]
Hi @Vasiharan,

It's not possible to rollback transactions via the REST API. However, take a look at [VCR](https://github.com/vcr/vcr). You can use this package to record HTTP requests and reference those in your unit tests. It won't allow you to maintain a !00% clean DB, since you'll still need to make an initial requests to record them. However, it will allow you run unit tests without creating a massive amount of test records that later need to be deleted.

Glad you like the package, hope that helps.

Best,
Matt
