### ISSUE TITLE
Laravel 5.2 Support?

### ISSUE THREAD

**Issue by JPT62089** [omniphx/forrest#73]
I know it just came out, but do you plan on supporting Laravel 5.2?

Thanks!

**Comment by omniphx** [comment]
Hi @JPT62089, of course I'll support it!

You might have noticed the error `Call to undefined method Illuminate\Foundation\Application::bindShared()`. That was due to the service provider was using a method that has been deprecated in Laravel 5, but wasn't removed until 5.2. 

Try installing the latest version of this package (2.0.5) and it should work fine with Laravel 5.2.

-Matt
