### ISSUE TITLE
Caching resources from Salesforce

### ISSUE THREAD

**Issue by mstephens** [omniphx/forrest#91]
Hello

When using the UserPassword authentication method and using `Forrest::authenticate` I notice it calls `->storeResources` upon each authentication, which then [fetches the resource list](https://github.com/omniphx/forrest/blob/master/src/Omniphx/Forrest/Client.php#L696).

This request each time gets a list of available resources from Salesforce, for example:
`{"tooling":"/services/data/v36.0/tooling","chatter":"/services/data/v36.0/chatter","tabs":"/services/data/v36.0/tabs","appMenu":"/services/data/v36.0/appMenu","quickActions":"/services/data/v36.0/quickActions","queryAll":"/services/data/v36.0/queryAll","commerce":"/services/data/v36.0/commerce","wave":"/services/data/v36.0/wave","exchange-connect":"/services/data/v36.0/exchange-connect",...}`

Would it make sense to cache this result rather than cause a x3 on each request (authenticate, get resources and original request)? :)

**Comment by mstephens** [comment]
Also, is there any reason for the UserPassword request why you authenticate each time? The `putTokenData` method stores them in cache, could you check before you run the `authenticate` logic?

Only mentioning to help improve :). It's an awesome project. If I get time I'm happy to contribute!

**Comment by omniphx** [comment]
Hi @mstephens, the only time it _should_ need to authenticate each request is if the token has expired. 

The basic pattern is for the package to do this:
1. Authenticate
2. Store/cache the token and available resources
3. Call a resource request (i.e., a SOQL query) and use the stored token
4. If that token is expired, refresh the token or with UserPassword simply authenticate again

At least on my end, it seems to be working correctly. Could you check your Saleforce org and see if how long the session expiration is for authentication tokens?

**Comment by mstephens** [comment]
@omniphx thanks for the reply!

The problem we're experiencing is say you've ten calls to Salesforce (doing various Salesforce requests) in your app, you cannot be sure you've an active token with `UserPassword` before the request (that's still valid). Therefore you **must** call the `Forrest::authenticate()` method before each Forrest request to ensure it's going to be successful. 

The Forrest `authenticate` method as a result then performs two requests:
1. Getting a new access token
2. Getting the resources available

In addition to the original request sent.

Traching this back, in the `storeResources` function there's:

    $resources = $this->resources(['format' => 'json']);
    $this->storage->put('resources', $resources);

Which we've temporarily replaced with:

    if(!$this->storage->has('resources')) {
        $resources = $this->resources(['format' => 'json']);
        $this->storage->put('resources', $resources);
    }

One thing that would be great is if the Omniphx Cache/Session classes could be modified for `put` to accept a time (as the Laravel cache does) that could then be used to store the session time set in configuration (via a configuration value).

Also, some way of caching the expiry time of the access token (via `UserPassword`)  for the main authenticate request, which then if still within that time frame doesn't make any subsequent ones. 

Hopefully this makes sense, we were quite quickly reaching our API limit without the above modification in place (we're still using the Auth request on each method).

**Comment by omniphx** [comment]
Hey @mstephens,

If a request is made with an expired token, the library will refresh/re-authenticate and try the request again. Anytime a request is made with an expired token, Salesforce will send back a 401 code which the library will catch and throw `TokenExpiredException`. So if that part is failing for some reason, you should still be able to catch that exception before trying the authentication again.

In terms of caching the resources as you suggested, I'm back and forth on that. It's definitely a great idea to cut down on the number of API requests. However, there is still some fringe cases where it might be valuable to refresh the resources. For instance, adding feature licenses to a user would give them more available resources. So I'll get back to you on the final solution.

In terms of configuring the session timeout, I initially choose not to include this since it configurable from within the Laravel app. The only use case would be if you wanted a timeout specific to the Salesforce package.

Let me know if that helps answer your concerns. I certainly understand the importance of avoiding the API limitations from my own personal experience, so if this package is not working how it is intended to I will definitely make those changes!

**Comment by mstephens** [comment]
@omniphx sounds good! Appreciate all the good work you've done!

With the `TokenExpiredException` this has to be caught throughout the application (i.e. wherever we're making calls to Forrest), is it possible to catch this from within the Forrest code itself, re-triggering automatically, without the need for a try/catch and repeated code?

**Comment by omniphx** [comment]
Hey @mstephens,

That's what it's supposed to do in the Client.php class:
```
    public function request($url, $options)
    {
        try {
            return $this->requestResource($url, $options);
        } catch (TokenExpiredException $e) {
            $this->refresh();
            return $this->requestResource($url, $options);
        }
    }
```

My concern was that perhaps it wasn't working properly on your end. In which case it might be safe to try to catch any exceptions and retry.
